delivery-service:
  cost.per.delivery: 2
  cost.per.product: 3
  fixed.cost: 2.99

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000

---

spring:
  profiles: test

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000