logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000

---

spring:
  profiles: test

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000