spring:
  jpa:
    hibernate:
      ddl-auto: create
    datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
      username: root
      password: 12345

---

spring:
  profiles: dev

  jpa:
    hibernate:
      ddl-auto: update