shopping-cart-service:
  minimum: 99
  maximum: 9999

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

spring:
  profiles: dev
  h2:
    console:
      enabled: true
  datasource:
    url: mysql://localhost:3307/shopping_cart
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
