shopping-cart-service:
  minimum: 99
  maximum: 9999

spring:
  profiles: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

spring:
  profiles: test
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/mysqltutorial?useSSL=false
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
